#Wed Nov 19 13:04:33 UTC 2025
micronaut:
  application:
    name: mn-stock-broker
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
      user: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:secret} #secret
      schemas: mn
      default-schema: mn

